In [4]:
import numpy as np
my_arr = np.arange(1000000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
my_list = list(range(1000000))

In [5]:
my_arr * 2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [12]:
%%time 
for _ in range(10): 
    my_arr2 = my_arr * 2

Wall time: 114 ms


In [8]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 5.08 s


In [9]:
%pwd

'D:\\wecloud\\datasci-program1'

In [13]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr.shape

(2, 3)

In [17]:
arr.ndim

2

In [18]:
arr = np.array((1,2,3))
arr

array([1, 2, 3])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(3,7,0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [23]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [40]:
np.indices((2,3))

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [27]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [28]:
arr.dtype

dtype('int32')

In [34]:
arr = np.array([[1., 2., 3],[4,5,6]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
arr.dtype

dtype('float64')

In [35]:
arr.strides

(24, 8)

In [36]:
arr.itemsize

8

In [37]:
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [39]:
arr[0,1,0]

4

In [41]:
arr = np.array([1,2,3])
arr + arr

array([2, 4, 6])

In [42]:
arr ** 2

array([1, 4, 9], dtype=int32)

In [43]:
arr % 2

array([1, 0, 1], dtype=int32)

In [44]:
arr > arr

array([False, False, False])

In [45]:
arr >= arr

array([ True,  True,  True])

In [46]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [48]:
arr[3:8] = 99
arr

array([ 0,  1,  2, 99, 99, 99, 99, 99,  8,  9])

numpy array slicing is reference, not copy

In [49]:
a = arr[3:8]
a[0] = 100
arr

array([  0,   1,   2, 100,  99,  99,  99,  99,   8,   9])

In [50]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [51]:
arr[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
arr[0][1]

array([5, 6, 7, 8])

In [53]:
arr[0,1]

array([5, 6, 7, 8])

In [56]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [58]:
arr[1, :, 2:] = 0
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10,  0,  0],
        [13, 14,  0,  0]]])

boolean indexing

In [60]:
data = np.random.randn(5,4)
data

array([[-0.90954039, -1.09725998,  0.20233699,  2.00248288],
       [ 2.16766029,  1.62444118, -1.27255622,  0.04316083],
       [-1.0321568 , -0.84008858, -0.98449316,  0.3713647 ],
       [ 0.07442878,  0.20173038,  0.01891762,  1.21592869],
       [-0.56764011, -1.02632087, -0.02235972,  1.08947516]])

In [61]:
data[[0,1,4]]

array([[-0.90954039, -1.09725998,  0.20233699,  2.00248288],
       [ 2.16766029,  1.62444118, -1.27255622,  0.04316083],
       [-0.56764011, -1.02632087, -0.02235972,  1.08947516]])

In [62]:
nindex = np.array([True, True, False, False, True])
nindex

array([ True,  True, False, False,  True])

In [63]:
data[nindex]

array([[-0.90954039, -1.09725998,  0.20233699,  2.00248288],
       [ 2.16766029,  1.62444118, -1.27255622,  0.04316083],
       [-0.56764011, -1.02632087, -0.02235972,  1.08947516]])

In [64]:
gender = np.array(['F', 'F', 'M', 'M', 'U'])
gender

array(['F', 'F', 'M', 'M', 'U'], dtype='<U1')

In [65]:
gender == 'F'

array([ True,  True, False, False, False])

In [67]:
data[gender != 'M']

array([[-0.90954039, -1.09725998,  0.20233699,  2.00248288],
       [ 2.16766029,  1.62444118, -1.27255622,  0.04316083],
       [-0.56764011, -1.02632087, -0.02235972,  1.08947516]])

In [68]:
data[gender == 'M']

array([[-1.0321568 , -0.84008858, -0.98449316,  0.3713647 ],
       [ 0.07442878,  0.20173038,  0.01891762,  1.21592869]])

In [69]:
data[gender == 'M', :2]

array([[-1.0321568 , -0.84008858],
       [ 0.07442878,  0.20173038]])

In [70]:
data[gender == 'M', 0]

array([-1.0321568 ,  0.07442878])

In [71]:
data > 2

array([[False, False, False,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [73]:
data[data>2]=2
data

array([[-0.90954039, -1.09725998,  0.20233699,  2.        ],
       [ 2.        ,  1.62444118, -1.27255622,  0.04316083],
       [-1.0321568 , -0.84008858, -0.98449316,  0.3713647 ],
       [ 0.07442878,  0.20173038,  0.01891762,  1.21592869],
       [-0.56764011, -1.02632087, -0.02235972,  1.08947516]])

In [74]:
data[data<0] =0
data

array([[0.        , 0.        , 0.20233699, 2.        ],
       [2.        , 1.62444118, 0.        , 0.04316083],
       [0.        , 0.        , 0.        , 0.3713647 ],
       [0.07442878, 0.20173038, 0.01891762, 1.21592869],
       [0.        , 0.        , 0.        , 1.08947516]])

In [75]:
data = np.zeros((8,4))
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
for i in range(8): data[i]=i
data

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [77]:
data[[0,1,2]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [79]:
data[[2,0,1,4]]

array([[2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [4., 4., 4., 4.]])

In [82]:
data = np.arange(32).reshape(8,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
data[[1,3,5,2],[1,1,2,2]]

In [83]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [84]:
data.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [85]:
np.dot(arr.T, arr)

array([[[[ 46,  56,  66,  76],
         [126, 136,   0,   0]],

        [[ 70,  88, 106, 124],
         [214, 232,   0,   0]]],


       [[[ 52,  64,  76,  88],
         [148, 160,   0,   0]],

        [[ 76,  96, 116, 136],
         [236, 256,   0,   0]]],


       [[[  3,   6,   9,  12],
         [ 27,  30,   0,   0]],

        [[  7,  14,  21,  28],
         [ 63,  70,   0,   0]]],


       [[[  4,   8,  12,  16],
         [ 36,  40,   0,   0]],

        [[  8,  16,  24,  32],
         [ 72,  80,   0,   0]]]])

In [86]:
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [87]:
a=arr.transpose((1,0,2))
a

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [88]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [89]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [91]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])